### PR TITLE
update mcm to v0.43.0

### PR DESCRIPTION
**Pull request by mwennrich**
- update mcm to v0.43.0
- update deps, go-version, alpine

### CODE REVIEW

**Comment by Gerrit91** [comment]
I would like to include / test this for the next Gardener version bump.

**Comment by mwennrich** [comment]
requires https://github.com/metal-stack/gardener-extension-provider-metal/pull/236

**Comment by Gerrit91** [comment]
Since we did not make it... can you please update to 0.44.0?

**Comment by mwennrich** [comment]
superseded by https://github.com/metal-stack/machine-controller-manager-provider-metal/pull/22

**Pull request closed without merging**
